### PR TITLE
[QOLDEV-933] drop redirection of private datasets

### PR DESCRIPTION
**Pull request by ThrawnCA**
- This is now a core feature, we don't need it in the plugin. We also need to adjust its behaviour to optionally give 404 on deleted datasets for PURL.

### CODE REVIEW

**Review by duttonw — APPROVED** [review]
tests plz

**Comment by ThrawnCA** [comment]
> tests plz

Do you mean tests here, or tests in core? Not sure how best to test a dropped feature.

**Comment by duttonw** [comment]
> > tests plz
> 
> Do you mean tests here, or tests in core? Not sure how best to test a dropped feature.

both

**Comment by ThrawnCA** [comment]
> both

We have tests for the login redirection both here and in infrastructure. They initially failed when the plugin feature was removed here, but are working with the core feature enabled.

**Pull request merged**
